apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  annotations:
    # Optional: Additional annotations for metadata
    # volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
spec:
  storageClassName: gp2  # Default storage class for EBS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Adjust storage size as needed
